from addons.web_extensions import WebExtensions
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP005
    Generated by: Channyke Rodriguez (csrodriguez21@ucatolica.edu.co)
    Generated on 10/13/2021, 00:47:17
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Dl_CRrVGkr6XQ2tp-Eg4dJ3yWlOTRQ7XPZwrxjLFM_0",
                              project_name="My first Project",
                              job_name="CP005")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """El sistema redirige al usuario a la pagina de cambio de prioridad, donde se muestra la interfaz para cambiar la prioridad de tareas según su ID."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/ActiveTime/"
    Idtarea = "25"
    Prioridad = "3"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Scroll window by ('0','62')
    driver.execute_script("window.scrollBy(0,62)")

    # 3. Click 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.click()

    # 4. Type 'jdme1' in 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.send_keys("jdme1")

    # 5. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 6. Type 'lindo123!' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("lindo123!")

    # 7. Click 'Log in'
    log_in = driver.find_element(By.CSS_SELECTOR,
                                 "#ingresar")
    log_in.click()

    # 8. Scroll window by ('0','400')
    driver.execute_script("window.scrollBy(0,400)")

    # 9. Navigate to 'http://localhost/ActiveTime/assets/pages/Agregar-Tarea/index2.html'
    driver.get(
        "http://localhost/ActiveTime/assets/pages/Agregar-Tarea/index2.html")

    # 10. Scroll window by ('0','399')
    driver.execute_script("window.scrollBy(0,399)")

    # 11. Click 'Change Priority'
    change_priority = driver.find_element(By.CSS_SELECTOR,
                                          "#changePriority")
    change_priority.click()

    # 12. Click 'task1'
    task1 = driver.find_element(By.CSS_SELECTOR,
                                "#idTask")
    task1.click()

    # 13. Type '{Idtarea}' in 'task1'
    task1 = driver.find_element(By.CSS_SELECTOR,
                                "#idTask")
    task1.send_keys(f'{Idtarea}')

    # 14. Click 'priority'
    priority = driver.find_element(By.CSS_SELECTOR,
                                   "#priority")
    priority.click()

    # 15. Select all '{Prioridad}' options in 'priority'
    priority = (By.CSS_SELECTOR, "#priority")
    driver.addons().execute(
        WebExtensions.selectoptionbyvalue(
            value=f'{Prioridad}'), *priority)

    # 16. Click 'priority'
    priority = driver.find_element(By.CSS_SELECTOR,
                                   "#priority")
    priority.click()

    # 17. Click 'Change'
    change = driver.find_element(By.CSS_SELECTOR,
                                 "#change-task")
    change.click()
